image: openjdk:16-alpine

stages:
    - build
    - release
cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

build:
    stage: build
    only:
        - 1.16.5
    script:
        - chmod +x ./gradlew
        - ./gradlew build
    # define path to collect artifacts
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week
release:
    stage: release
    when: manual
    image: registry.gitlab.com/gitlab-org/release-cli
    script:
        - echo "fabric release"
    except:
        - tags
    release:
        tag_name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
        description: "fabric-release-${CI_COMMIT_REF_NAME}"