image: openjdk:16-alpine

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches
build:
    only:
        - 1.16.5
    script:
        - chmod +x ./gradlew
        - ./gradlew build
    # define path to collect artifacts
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week
release:
    only:
        - tags
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    script:
        - echo "release job"
    release:
        tag_name: $CI_COMMIT_TAG
        description: "Fabric release"