version: 2
jobs:
  build:
    docker:
      - image: gradle:jdk24-alpine@sha256:74bfafd694dca47440b22d3c41d6b98a9d15c09d0befbb065a1d9d883cd3a224
    steps:
      - checkout
      - run: gradle build
      - store_artifacts:
          path: build/libs
