version: 2
jobs:
  build:
    docker:
      - image: docker.io/theoparis/graalvm:24@sha256:d16b0f7a0cd2e02dabd37837f342ee5b6c4254e60eaf77b6141109ae57395e2e
    steps:
      - checkout
      - run: ./gradlew build
      - store_artifacts:
          path: build/libs
