version: 2
jobs:
  build:
    docker:
      - image: gradle:jdk24-alpine@sha256:99507bfc8f779a422ae533c5416c853304eeab466bcf5f5c0441833c5ba96f9b
    steps:
      - checkout
      - run: gradle build
      - store_artifacts:
          path: build/libs
